name       : autoconf
version    : '2.70'
release    : 6
source     :
    - http://ftp.gnu.org/gnu/autoconf/autoconf-2.70.tar.xz : fa9e227860d9d845c0a07f63b88c8d7a2ae1aa2345fb619384bb8accc19fecc6
homepage   : http://www.gnu.org/software/autoconf/
license    : GPL-2.0-or-later
summary    : Autoconf is an extensible package of M4 macros that produce shell scripts to automatically configure software source code packages.
component  : system.devel
description: |
    Autoconf creates a configuration script for a package from a template file that lists the operating system features that the package can use, in the form of M4 macro calls.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
