name        : autoconf
version     : 2.69
release     : 4
source      :
    - http://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.xz : 64ebcec9f8ac5b2487125a86a7760d2591ac9e1d3dbd59489633f9de62a57684
homepage    : http://www.gnu.org/software/autoconf/
license     :
    - GPL-2.0
summary     : Autoconf is an extensible package of M4 macros that produce shell scripts to automatically configure software source code packages.
component   : system.devel
description : |
    Autoconf creates a configuration script for a package from a template file that lists the operating system features that the package can use, in the form of M4 macro calls.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
