name       : autoconf
version    : '2.71'
release    : 11
source     :
    - https://ftp.gnu.org/gnu/autoconf/autoconf-2.71.tar.xz : f14c83cfebcc9427f2c3cea7258bd90df972d92eb26752da4ddad81c87a0faa4
homepage   : http://www.gnu.org/software/autoconf/
license    : GPL-2.0-or-later
summary    : Autoconf is an extensible package of M4 macros that produce shell scripts to automatically configure software source code packages.
component  : system.devel
description: |
    Autoconf creates a configuration script for a package from a template file that lists the operating system features that the package can use, in the form of M4 macro calls.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
check      : |
    # WARNING: takes a while
    # NOTED FAIL: parallel autotest and signal handling
    %make check || :
